### ISSUE TITLE
npm is not installing properly?

### ISSUE THREAD

**Issue by vamse15** [flyve-mdm/web-mdm-dashboard#1014]
Hello guys, i am new guy on flyvemdm web dashboard side, I installing the the npm by using command npm install, here i getting issue. Here i attached the screen shot of the issue, please give me solution on this issue.

/home/saimdm/Pictures/Screenshot from 2018-07-23 17-54-45.png

Thanks,
Vamse

**Comment by vamse15** [comment]
![npm_install_issue](https://user-images.githubusercontent.com/28727493/43255140-a0911584-90e6-11e8-8328-06827b71303c.png)

**Comment by Gianfranco97** [comment]
@vamse15 Please update to the latest version of the application, make sure you have installed the latest long-time support version of NodeJS and NPM, and reinstall the dependencies of the project. We use Yarn in the script of our project, so also make sure you have installed the latest version of it.
