### ISSUE TITLE
Activation email

### ISSUE THREAD

**Issue by vamse15** [flyve-mdm/web-mdm-dashboard#1031]
Hello Guys, I installed web mdm dashboard after i sing up with email address, but I didn't received the Activation email from Flyvemdm web dashboard for login into flymdm web dashboard.

Applications versions list:
Glpi                                -- GLPI 9.2.4
flymdm                           -- 2.0.0-rc2
fusioninventory              -- 9.2+1.0
Web MDM Dashboard   -- 1.0.0-dev
Flyve MDM Demo          -- 1.0.0-dev

  Here i attached the screen shots regarding sing in issue, could you please give me some solution on this issue. 

Thanks & Regards,
Vamsekrishna
![screenshot from 2018-07-30 14-52-07](https://user-images.githubusercontent.com/28727493/43456511-5ff94786-94e1-11e8-9b9e-42356fcdbc76.png)
![screenshot from 2018-07-30 14-55-17](https://user-images.githubusercontent.com/28727493/43456515-648176a2-94e1-11e8-9d57-046842f5d637.png)

**Comment by hectorerb** [comment]
Hi @vamse15, It's likely that the server takes a while to send the activation email. Let me check I'm trying to replicate the steps and observe the behavior

**Comment by hectorerb** [comment]
Hi @vamse15 I have opened an issue reporting this error https://github.com/flyve-mdm/glpi-plugin/issues/672

**Comment by Gianfranco97** [comment]
Closed: https://github.com/flyve-mdm/glpi-plugin/issues/672

The demo mode is abandoned
