### ISSUE TITLE
Add versioning for gh-pages branch

### ISSUE THREAD

**Issue by Naylin15** [flyve-mdm/web-mdm-dashboard#1065]
### Observed Results:
We must add the versioning for the coverage and code documentation on gh-pages

  
### Expected behavior:
To have the documentation for develop, master and support branches

**Comment by Naylin15** [comment]
Hi 

The project site can display the information for the different branches, develop, master and support as stated in #1075 

Closing this issue

**Comment by ajsb85** [comment]
Hi, @Naylin15 
The project site of the MDM Agent support coming soon page 😃 
But this project site of the Web Dashboard no. Shows a 404 error page.

![image](https://user-images.githubusercontent.com/663460/46022037-245cbf00-c0e2-11e8-9e96-58249e347712.png)

**Comment by Naylin15** [comment]
I'll check right away 👍
