### ISSUE TITLE
Can't upload APK files

### ISSUE THREAD

**Issue by DIOHz0r** [flyve-mdm/web-mdm-dashboard#1093]
**Describe the bug**

**To Reproduce**
1. Go to https://demo-dashboard.flyve.org
2. Click on Applications
3. Try to add a new apk

**Expected behavior**
Allow the file to be uploaded or at least a message text

**Screenshots**
![imagen](https://user-images.githubusercontent.com/1426313/45506754-33488680-b75e-11e8-9d1f-6cdd3ba0fb8a.png)

**Comment by Gianfranco97** [comment]
Closed in: https://github.com/flyve-mdm/web-mdm-dashboard/pull/1086
