### ISSUE TITLE
Language not changing

### ISSUE THREAD

**Issue by Naylin15** [flyve-mdm/web-mdm-dashboard#1095]
**Describe the bug**
The language is not changing

**To Reproduce**
1. Go to demo-dashboard.flyve.org
2. Change language
3. See no change in language

**Expected behavior**

**Screenshots**

![captura de pantalla 2018-09-13 a la s 3 04 55 p m](https://user-images.githubusercontent.com/30867977/45509848-a229dd80-b766-11e8-98cd-8349b4033734.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: chrome
 - Version 68

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ajsb85** [comment]
https://dev.flyve.org/dashboard/app/settings/display

**Comment by Gianfranco97** [comment]
Done, translations working normally

![captura de pantalla 2018-12-14 a la s 4 00 09 p m](https://user-images.githubusercontent.com/19965590/50024660-8201f880-ffb9-11e8-8474-2ae47ffa3ddc.png)
