### ISSUE TITLE
Dashboard freezes on file deletion

### ISSUE THREAD

**Issue by DIOHz0r** [flyve-mdm/web-mdm-dashboard#1097]
**Describe the bug**

**To Reproduce**
1. Go to https://demo-dashboard.flyve.org
2. Click on files and select one
3. Click on trash can icon to delete the file
4. Try to click on any place and see the error

To exit the problem you have to reload the web page.

**Expected behavior**
Allow the deletion of the file

**Comment by Gianfranco97** [comment]
I do not find any problem with this screen. If the error repeats, let us know

![test](https://user-images.githubusercontent.com/19965590/45849711-22b98280-bd01-11e8-8654-a834469b5a54.gif)
