### ISSUE TITLE
Meta criteria support in the search engine UI

### ISSUE THREAD

**Issue by btry** [flyve-mdm/web-mdm-dashboard#1099]
Hi, @flyve-mdm/frontend-development 

GLPI allows to do complex searches using meta criteria.

We need to ad this feature. Read the search examples in the API documentation.

https://github.com/glpi-project/glpi/blob/9.3/bugfixes/apirest.md#search-items

/cc @orthagh

**Comment by CharlyJazz** [comment]
I do not know, ask the authors of this [file](https://github.com/flyve-mdm/web-mdm-dashboard/blob/develop/src/containers/SearchEngine/actions.js)
