### ISSUE TITLE
Cannot login on Dev environment

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/web-mdm-dashboard#1100]
**Describe the bug**
Login on https://dev.flyve.org/dashboard/ show an error without description

<img width="865" alt="captura de pantalla 2018-09-17 a la s 5 19 10 p m" src="https://user-images.githubusercontent.com/4085091/45650965-fbaf4680-ba9d-11e8-8ac0-51d8325eb426.png">

**To Reproduce**
1. Go to url
2. Add my user and password

**Expected behavior**
Login in to the dashboard

**Comment by Gianfranco97** [comment]
With my user works perfectly, check your credentials, if the problem persists let us know

![login](https://user-images.githubusercontent.com/19965590/46034761-7a743700-c0cf-11e8-9ec3-9b1d69373db0.gif)
