### ISSUE TITLE
Delete Device vs Wipe Device vs Unenrollment Device

### ISSUE THREAD

**Issue by betweenbrain** [flyve-mdm/web-mdm-dashboard#1113]
**Describe the bug**
Hello,
I'm confused by what _Delete Device_ vs _Wipe Device_ vs _Unenrollment Device_ is under _Danger Zone_. I understand that Wipe Device will delete all of the information on it, but Delete Device sounds very similar. But, _Delete Device_ could also be confused with _Unenrollment Device_ .

**To Reproduce**
1. Go to https://demo-dashboard.flyve.org/app/devices
2. Click on a device
3. Click on _Danger Zone_

**Expected behavior**
Clarity of what each of the three features do.

**Screenshots**
![screen shot 2018-10-01 at 6 09 05 pm](https://user-images.githubusercontent.com/634119/46318622-27095980-c5a5-11e8-987b-55e66dbc274c.png)

**Comment by betweenbrain** [comment]
Hi @Naylin15,
Thanks for the link to https://flyvemdm-doc.readthedocs.io, I haven't found that before. Is that the location of the latest and most complete documentation?

**Comment by Gianfranco97** [comment]
Yes @betweenbrain, that's the latest version

**Comment by ajsb85** [comment]
Hi, @btry 
Could you help us with this issue and clarify the difference?
I will close this issue but we need to keep this question as knowledge base.

**Comment by btry** [comment]
Hi

- Delete = remove it from the database
- Wipe = send a wipe request to the device (in case of loss or theft). The device is kept in the DB.
- Unenroll = send a unenroollment request to the device. The device is kept in the DB.
