### ISSUE TITLE
MDM Web Dashboard landing page issues

### ISSUE THREAD

**Issue by iorfmer** [flyve-mdm/web-mdm-dashboard#1176]
After mdm web dashboard sudo docker-compose up --build command successfully and trying to access landing page:

### Observed Results:

Debug mode: After login with all default glpi possible users, it always shows an error "Error no internet connection" with a message in the upper right side. No Apache activity is shown in the console.

Production mode: Login page is correctly served by Apache:

Dashboard-apache    | x.x.x.x - - [06/Nov/2018:15:53:52 +0000] "GET / HTTP/1.1" 200 5207
Dashboard-apache    | x.x.x.x - - [06/Nov/2018:15:53:53 +0000] "GET /dashboard/css/leaflet.css HTTP/1.1" 200 5207
Dashboard-apache    | x.x.x.x - - [06/Nov/2018:15:53:53 +0000] "GET /dashboard/config.js HTTP/1.1" 200 5207
Dashboard-apache    | x.x.x.x - - [06/Nov/2018:15:53:53 +0000] "GET /dashboard/static/js/54.0b599fb0.chunk.js HTTP/1.1" 200 5207
Dashboard-apache    | x.x.x.x - - [06/Nov/2018:15:53:53 +0000] "GET /dashboard/static/css/main.d8450ca0.chunk.css HTTP/1.1" 200 5207
Dashboard-apache    | x.x.x.x - - [06/Nov/2018:15:53:53 +0000] "GET /dashboard/static/js/main.45016fbf.chunk.js HTTP/1.1" 200 5207
Dashboard-apache    | x.x.x.x - - [06/Nov/2018:15:53:53 +0000] "GET /dashboard/apple-touch-icon.png HTTP/1.1" 200 5207
Dashboard-apache    | x.x.x.x - - [06/Nov/2018:15:53:53 +0000] "GET /dashboard/images/favicon.png HTTP/1.1" 200 5207

But no content is rendered in browser, it shows these errors in the development console:

SyntaxError: expected expression, got '<' config.js:1
SyntaxError: expected expression, got '<' 54.0b599fb0.chunk.js:1
SyntaxError: expected expression, got '<' main.45016fbf.chunk.js:1
[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIContentSniffer.getMIMETypeFromContent]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 181"  data: no] 

Many thanks.

**Comment by ajsb85** [comment]
Hi, @iorfmer 
Looks like you forgot to modify the config file.

` /dashboard/config.js`

**Comment by iorfmer** [comment]
Hi @ajsb85,
I have filled it with glpi API link:

window.appConfig = {
  glpiApiLink: 'http://dev.glpi.local/apirest.php/',
  appName: 'MDM Dashboard',
  bugsnag: 'your_bugsnag_key',
}

Did I miss something?

Many thanks for your quick response.

**Comment by ajsb85** [comment]
Take a look in your config file from the Web Browser.

Example URL
https://dev.flyve.org/dashboard/config.js

Our dev environment example:
```JS
window.appConfig = {
  glpiApiLink: "https://dev.flyve.org/glpi/apirest.php",
  demoToken: "pe90W27ebPXIeYXsj2mYE0nMrRz9q1AlguKhbhcI",
  pluginToken: "2JoAOqcPcqkMZDf2QeeQBAVjERO2LamlZghkvWPB",
  appName: "MDM Dashboard",
  bugsnag: "fba7440f31b8f7a7e72495cf000b2c42"
}
```

**Comment by iorfmer** [comment]
Without domain redirection, it shows me a 404 error. I will redirect it to an url and try again. By the way, these fields value, where they came from? 
```

demoToken: "pe90W27ebPXIeYXsj2mYE0nMrRz9q1AlguKhbhcI",
pluginToken: "2JoAOqcPcqkMZDf2QeeQBAVjERO2LamlZghkvWPB",
```

Many thanks for your help.

**Comment by ajsb85** [comment]
No needed anymore

Reference:
https://git.io/fpf4T

**Comment by iorfmer** [comment]
Hi again,

I have re installed again web-mdm-dashboard, and we payed attention to this error when we perform npm run-script build. Here it is npm-debug.log content:

 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run-script', 'build' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle web-admin-dashboard@2.0.0-rc.2~prebuild: web-admin-dashboard@2.0.0-rc.2
6 silly lifecycle web-admin-dashboard@2.0.0-rc.2~prebuild: no script for prebuild, continuing
7 info lifecycle web-admin-dashboard@2.0.0-rc.2~build: web-admin-dashboard@2.0.0-rc.2
8 verbose lifecycle web-admin-dashboard@2.0.0-rc.2~build: unsafe-perm in lifecycle true
9 verbose lifecycle web-admin-dashboard@2.0.0-rc.2~build: PATH: /usr/share/npm/bin/node-gyp-bin:/home/froi_mercade/web-mdm-dashboard/node_mod$
10 verbose lifecycle web-admin-dashboard@2.0.0-rc.2~build: CWD: /home/froi_mercade/web-mdm-dashboard
11 silly lifecycle web-admin-dashboard@2.0.0-rc.2~build: Args: [ '-c',
11 silly lifecycle   'yarn lint && NODE_PATH=./src react-scripts build && node ./ci/scripts/create_htaccess.js' ]
12 silly lifecycle web-admin-dashboard@2.0.0-rc.2~build: Returned: code: 1  signal: null
13 info lifecycle web-admin-dashboard@2.0.0-rc.2~build: Failed to exec build script
14 verbose stack Error: web-admin-dashboard@2.0.0-rc.2 build: `yarn lint && NODE_PATH=./src react-scripts build && node ./ci/scripts/create_h$
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid web-admin-dashboard@2.0.0-rc.2
16 verbose cwd /home/froi_mercade/web-mdm-dashboard/public
17 error Linux 4.15.0-1023-gcp
18 error argv "/usr/bin/node" "/usr/bin/npm" "run-script" "build"
19 error node v8.10.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error web-admin-dashboard@2.0.0-rc.2 build: `yarn lint && NODE_PATH=./src react-scripts build && node ./ci/scripts/create_htaccess.js`
22 error Exit status 1
23 error Failed at the web-admin-dashboard@2.0.0-rc.2 build script 'yarn lint && NODE_PATH=./src react-scripts build && node ./ci/scripts/cre$
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the web-admin-dashboard package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     yarn lint && NODE_PATH=./src react-scripts build && node ./ci/scripts/create_htaccess.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs web-admin-dashboard
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls web-admin-dashboard
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

Many thanks for your help!

**Comment by iorfmer** [comment]
Solved, we had a problem with Node version. It took Ubuntu default Node version instead of the latest one installed by npm. We upgraded Ubuntu's Node version by their repos using apt-get and it worked.

Many thanks! We have ranked your repos.

Kind regards.
