### ISSUE TITLE
APK upload not available on demo

### ISSUE THREAD

**Issue by DIOHz0r** [flyve-mdm/web-mdm-dashboard#1192]
**Describe the bug**
Hi, the site https://demo-dashboard.flyve.org has a problem uploading APKs, for some reason it throws a 401 code but if I use the same credentials on https://demo-api.flyve.org and upload the APK through GLPI UI the file can be uploaded.

**To Reproduce**
1. Go to applications
2. Click on new application
3. Try to upload the file.

**Additional context**
Files upload is working ok

**Comment by ajsb85** [comment]
Hi, @diohz0r 
Could you confirm if this issue is still present in the new Web Dashboard in the dev env?

**Comment by DIOHz0r** [comment]
I tested it on dev and worked however the issue is on the demo, the plugin and dashboard must be updated there by @farfou to test it again.

**Comment by ajsb85** [comment]
Hi, @DIOHz0r 
I will close the issue, if it persist let's re-open it.
Thank you.
