### ISSUE TITLE
Add phone number in the devices

### ISSUE THREAD

**Issue by CamposErik** [flyve-mdm/web-mdm-dashboard#1193]
**Is your feature request related to a problem? Please describe.**
Show the phone number to get it and with that send a Ping SMS in the android dashboard.

**Describe the solution you'd like**
In the devices, in the agent system report, put a section with the agent phone number. 

I find an example about how to get the last contacts data.
https://github.com/flyve-mdm/glpi-plugin/issues/803

**Comment by Gianfranco97** [comment]
![photo6043972610401873681](https://user-images.githubusercontent.com/19965590/49085512-8cd23480-f228-11e8-9199-5fe1b327069a.jpg)

If you have the agent ID you can find the computer. From the computer, get the item_devicesimcard, and from it, get the line
