### ISSUE TITLE
Deployment Errors

### ISSUE THREAD

**Issue by Greenstonetr** [flyve-mdm/web-mdm-dashboard#1199]
Hi 
I am from Turkey.

SORRY My English.

My Flyve MDM Dashboard is not running correctly.

I cannot deploy a file or app  to Android Tablet.

There is some errors:

1-) From Android MQTT Error

![error-1](https://user-images.githubusercontent.com/43892434/49569577-60fc3080-f945-11e8-9f86-ec2158a4d44f.png)

2-) From Android Tablet Message Box

"Application Not Found in List of Installed Applications"

3-) Fusion Inventory Package Management Settings

![fusioninventory_package_management](https://user-images.githubusercontent.com/43892434/49569741-d5cf6a80-f945-11e8-809b-5e9a95165989.PNG)

4-) Fusion Inventory Deploy Mirror Servers

![deploy_mirror](https://user-images.githubusercontent.com/43892434/49569818-0fa07100-f946-11e8-9985-d2ae2037a5de.PNG)

My Linux Screen shoots

![linux](https://user-images.githubusercontent.com/43892434/49569883-38c10180-f946-11e8-9776-4dff6007787a.PNG)

Note:

Android Tablet Samsung SM P600

**Comment by Gianfranco97** [comment]
@Greenstonetr Are you working with a local instance or are you using the 'demo' environment?

**Comment by ajsb85** [comment]
Duplicated https://github.com/flyve-mdm/android-mdm-agent/issues/643
