### ISSUE TITLE
The 'dev' environment doesn't work

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/web-mdm-dashboard#1200]
**Describe the bug**
It isn't possible to find the js file.
```
Refused to execute script from 'https://dev.flyve.org/dashboard/static/js/main.6d8be742.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```
**To Reproduce**
1. Go to 'https://dev.flyve.org/'
2. See error

**Screenshots**
![captura de pantalla 2018-12-06 a la s 12 43 04 p m](https://user-images.githubusercontent.com/19965590/49599220-d15f7d80-f956-11e8-82fd-09106daccd51.png)

**Comment by ajsb85** [comment]
I fix it 😎
