### ISSUE TITLE
File and app size limit

### ISSUE THREAD

**Issue by Greenstonetr** [flyve-mdm/web-mdm-dashboard#1223]
How to change upload file size limit. Because I can not upload file and app bigger than 5 MB.

**Comment by DIOHz0r** [comment]
Hi, 

First for all you have to check those settings on your server where is GLPI hosted and adjusts those values https://stackoverflow.com/a/2184541/10643422

**Comment by Greenstonetr** [comment]
I changed php.ini maximum upload file size limit.
GLPI/Plugings/FlyveMDM I can upload 50Mbyte files or app But I can't upload dashboard big file or app

**Comment by Gianfranco97** [comment]
Files limit: https://github.com/flyve-mdm/web-mdm-dashboard/blob/df25b2130c5bc3514cd9f2d0dbedbc11a9f93ba3/src/containers/Files/components/FilesAdd.js#L160

Apps limit: https://github.com/flyve-mdm/web-mdm-dashboard/blob/df25b2130c5bc3514cd9f2d0dbedbc11a9f93ba3/src/containers/Applications/components/ApplicationsAdd.js#L212
