### ISSUE TITLE
On Dashboard Device Offline seen

### ISSUE THREAD

**Issue by Greenstonetr** [flyve-mdm/web-mdm-dashboard#1224]
I can ping SUCCESFULLY But Device Status Offline in DASHBOARD.
What can I do ?

**Comment by Gianfranco97** [comment]
That is a problem of the agent and the plugin, the dashboard simply shows the values ​​that the plugin returns

**Comment by Gianfranco97** [comment]
I opened an issue in the plugin to notify the problem
