### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Palsofty** [flyve-mdm/web-mdm-dashboard#1237]
info Commands available from binary scripts: acorn, acorn.cmd, ansi-html, ansi-html.cmd, atob, atob.cmd, autoprefixer,
autoprefixer.cmd, babylon, babylon.cmd, browserslist, browserslist.cmd, chrome-remote-interface, chrome-remote-interface.cmd, conventional-changelog-writer, conventional-changelog-writer.cmd, conventional-commits-parser, conventional-commits-parser.cmd, conventional-github-releaser, conventional-github-releaser.cmd, conventional-recommended-bump, conventional-recommended-bump.cmd, cssesc, cssesc.cmd, cypress, cypress.cmd, detect, detect-libc, detect-libc.cmd, detect-port, detect-port.cmd, detect.cmd, errno, errno.cmd, escodegen, escodegen.cmd, esgenerate, esgenerate.cmd, eslint, eslint.cmd, esparse, esparse.cmd, esvalidate, esvalidate.cmd, extract-zip, extract-zip.cmd, get-pkg-repo, get-pkg-repo.cmd, gh-pages, gh-pages-clean, gh-pages-clean.cmd, gh-pages.cmd, git-raw-commits, git-raw-commits.cmd, git-semver-tags, git-semver-tags.cmd, github-release, github-release.cmd, handlebars, handlebars.cmd, he, he.cmd, hint, hint.cmd, html-minifier, html-minifier.cmd, image-size, image-size.cmd, import-local-fixture, import-local-fixture.cmd, in-install, in-install.cmd, in-publish, in-publish.cmd, is-ci, is-ci.cmd, jest, jest-runtime, jest-runtime.cmd, jest.cmd, js-yaml, js-yaml.cmd, jsdoc, jsdoc.cmd, jsesc, jsesc.cmd, json5, json5.cmd, JSONStream, JSONStream.cmd, loose-envify, loose-envify.cmd, marked, marked.cmd, miller-rabin, miller-rabin.cmd, mime, mime.cmd, mkdirp, mkdirp.cmd, multicast-dns, multicast-dns.cmd,
nearley-railroad, nearley-railroad.cmd, nearley-test, nearley-test.cmd, nearley-unparse, nearley-unparse.cmd, nearleyc, nearleyc.cmd, needle, needle.cmd, node-gyp, node-gyp.cmd, node-pre-gyp, node-pre-gyp.cmd, node-sass, node-sass.cmd, nopt, nopt.cmd, not-in-install, not-in-install.cmd, not-in-publish, not-in-publish.cmd, parser, parser.cmd, prebuild-install, prebuild-install.cmd, prettier, prettier.cmd, rc, rc.cmd, react-scripts, react-scripts.cmd, regjsparser, regjsparser.cmd, rimraf, rimraf.cmd, sane, sane.cmd, sassgraph, sassgraph.cmd, semver, semver.cmd, sha.js, sha.js.cmd, sshpk-conv, sshpk-conv.cmd, sshpk-sign, sshpk-sign.cmd, sshpk-verify, sshpk-verify.cmd, standard-version, standard-version.cmd,
strip-indent, strip-indent.cmd, svgo, svgo.cmd, terser, terser.cmd, uglifyjs, uglifyjs.cmd, uuid, uuid.cmd, watch, watch.cmd, webpack, webpack-dev-server, webpack-dev-server.cmd, webpack.cmd, which, which.cmd
info Project commands
   - build
      yarn lint && NODE_PATH=./src react-scripts build && node ./ci/scripts/create_htaccess.js
   - coverage
      NODE_PATH=./src yarn test --coverage
   - docs
      yarn jsdoc src -r -d docs -t ./jsdoc_theme
   - eject
      react-scripts eject
   - gh-pages-changelog
      yarn gh-pages --dist ./ --src '{./CHANGELOG.md,CHANGELOG.md}' --dest ./_includes --add
   - gh-pages-coverage
      yarn gh-pages --dist coverage
   - gh-pages-docs
      yarn gh-pages --dist docs
   - gh-pages-reports
      yarn gh-pages --dist reports --dest reports
   - gh-pages-screenshots
      yarn gh-pages --dist cypress/screenshots --dest screenshots
   - lint
      yarn eslint src --fix
   - release
      yarn standard-version
   - start
      NODE_PATH=./src react-scripts start
   - test
      NODE_PATH=./src yarn react-scripts test
   - test:cypress
      yarn cypress run
   - test:cypress-open
      yarn cypress open
   - test:watch
      NODE_PATH=./src yarn test --watch
   - test:webhint
      node node_modules/hint/dist/src/bin/hint.js http://localhost:3000/
question Which command would you like to run?:

**Comment by Gianfranco97** [comment]
Hi @Palsofty, I not have been able to replicate the error. I was testing and the installation worked correctly. Make sure you have downloaded the latest version of the project. If the problem persists let us know. 

Best regards.
