### ISSUE TITLE
How-tos and development documentation

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/web-mdm-dashboard#124]
Hi, @Naylin15 

Change the name "Wiki" to "How-tos" and add these articles; and add the sub menu items to the Development section. If these pages does not exist, please, create an issue and request it. 👍 

**How-tos**

- [x] How to install
- [x] How to use
- [x] Use Cases
- [x] How it works
- [x] How to contribute
- [x] How to Translate

**Development**

- [x] Code documentation
- [x] Code coverage
- [x] Test report

**Comment by Naylin15** [comment]
Added how to use article in [982a18d](https://github.com/flyve-mdm/web-mdm-dashboard/commit/982a18d299fdee7df071d66fac6f23dc0b1a0ccc)

**Comment by Naylin15** [comment]
Added the sub menu items to development section in [36e8330](https://github.com/flyve-mdm/web-mdm-dashboard/commit/36e83302107f16bb548a7b5fb3b78f37a6c3fcba)
Now working on the use cases article

**Comment by Naylin15** [comment]
Progress on the use cases article on [Hackmd](https://hackmd.io/BwUxCMBMU4FoDsAzSk4BZwEY0E4AMSAhogKyn4BsWS+pATJPkA==?both) still working on it

**Comment by Naylin15** [comment]
Added use cases article in [ad6e0f5](https://github.com/flyve-mdm/web-mdm-dashboard/commit/ad6e0f5e1ef01de8fecb216e60157e61785bd197), adding the coverage on the gh-pages branch

**Comment by Naylin15** [comment]
I'm improving the coverage display, it looks like this right now in local

![Coverage on local](https://user-images.githubusercontent.com/30867977/35169533-42275676-fd33-11e7-9955-ceaaef8edfca.png)

**Comment by ajsb85** [comment]
We need to add the coverage report inside the Project Site layout.

**Comment by Naylin15** [comment]
I'm making the changes on this PR [#240](https://github.com/flyve-mdm/web-mdm-dashboard/pull/240)

**Comment by Naylin15** [comment]
I'm working on the draft of how to install article, and I'll be fixing the CSS Lints issues mentioned on the PR #240

**Comment by Naylin15** [comment]
Progress on the installation article in [Hackmd](https://hackmd.io/JzAcCNgdlBmBaALIgjOJwAMBWe5bi5QBMKxoApuQIbVhA===?both)

The css lint issues are being solved on the PR #243
