### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by CharlyJazz** [flyve-mdm/web-mdm-dashboard#256]
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Support request => Please do not submit support request here, instead see https://github.com/flyve-mdm/web-mdm-dashboard/blob/develop/CONTRIBUTING.md#questions-or-doubts

## Current behavior

I have cloned the repository, and edited the config.json file as described in this article:
http://flyve.org/web-mdm-dashboard/howtos/contributors

I already installed the dependencies and run the development server with `npm run start` in the port 3000

And the bug appear:

![image](https://user-images.githubusercontent.com/12489333/35362636-82a50aba-013c-11e8-83b8-1f1fd0314bcd.png)

![image](https://user-images.githubusercontent.com/12489333/35362659-9cade116-013c-11e8-95b0-f3e678f6c728.png)

## Expected behavior

I should show the page correctly

## Minimal reproduction of the problem with instructions

1. Clone de repo
2. Run `npm install`
3. Edit config.json with the credentials descripted in this [article](http://flyve.org/web-mdm-dashboard/howtos/contributors)
4. Run `npm run start`

**Comment by Gianfranco97** [comment]
@CharlyJazz I tried to reproduce your error but I am not able to, I think you're doing something wrong.
The steps to follow are those:
- git clone git@github.com:flyve-mdm/web-mdm-dashboard.git
- cd web-mdm-dashboard/
-  npm install
- enter the file 'src / config.json' and change the values of URL_GLPI_API and USER_TOKEN, as indicated in the article http://flyve.org/web-mdm-dashboard/howtos/contributors
- npm run start

**Comment by Gianfranco97** [comment]
@CharlyJazz one of the things that could causing the error is the version you are using from the library of 'javascript-library-glpi'. to solve this you must clean the npm cache before installing the project libraries. 

- npm cache clean
