### ISSUE TITLE
Can't resolve 'javascript-library-glpi'

### ISSUE THREAD

**Issue by Robertbaelde** [flyve-mdm/web-mdm-dashboard#291]
### Observed Results:

When i try to run a fresh install of the dashboard, i get a error that javascript-library-glpi cannot be resolved. 

```
./src/AdminDashboard/HeaderAdminDashboard.js
Module not found: Can't resolve 'javascript-library-glpi' in '/code/web-mdm-dashboard/src/AdminDashboard'
```

  
### Expected behavior:

It shouldn't have the error.

**Comment by ajsb85** [comment]
Hi, @Robertbaelde 

Here is the library:
git@github.com:glpi-project/javascript-library-glpi.git

We moved the library to the @glpi-project org.
https://www.npmjs.com/package/@teclib/glpi-api-client

@Gianfranco97 here is the error:
https://git.io/vNxzX
