### ISSUE TITLE
Translations and support to I18N/L10N

### ISSUE THREAD

**Issue by CharlyJazz** [flyve-mdm/web-mdm-dashboard#294]
### Observed Results:

The application does not support multiple languages
  
### Expected behavior:

The application should have the functionality to change the language in which messages and and all static texts are rendered

---------------------
It is necessary to investigate what is the best technology to implement multiple languages in the application

Options:

- [ ] Transifex CLI
- [x] WinJS (I18N/L10N)
- [x] React (I18N/L10N)

### Testing and CI:

- A series of automated tests should be created to verify if the translations behave as they should.
- The status of the application will be monitored by CircleCI and not by TravisCI

### Libraries to test feasibility

- https://github.com/JSxMachina/react-i18nify
- https://github.com/NunoPinheiro/react-i18n-helper

### react-i18n-helper: 

[Example](https://react-theme-1.herokuapp.com/)

This is a simple way to implement i18n in a React application using Redux and a High Order Component to wrap the entire application

The necessary libraries are:
- node-polyglot (Translation tools)
- redux (state manager)

**Important**: 

- The library https://github.com/JSxMachina/react-i18nify is not used directly, since the code is flawed and depends of libraries that are not necessary for our projects, such as `promise-polyfill`. Instead it was refactored and i created the HOC.

- The strings of each translation are not added to the bundle file of the application which prevents it from increasing its size:

![image](https://user-images.githubusercontent.com/12489333/35882380-63d0fc7a-0b5a-11e8-8307-c2c43a0c1a30.png)

### react-i18nify:
[In this example the library is used to enable i18n](https://streamable.com/knbsc)

**Important**:  Is more complicated to use, and if it is used in the way you show in your documentation, all the strings of each language will be added in the bundle file of the application and will be heavie:

![image](https://user-images.githubusercontent.com/12489333/35882407-7bdcc5ba-0b5a-11e8-898f-76dd45ff635a.png)

**Comment by CharlyJazz** [comment]
WinJS (I18N/L10N):

According to [this](https://github.com/winjs/winjs/issues/1163), I think there is not a native WinJS form for localization and internalization available for the web application.

@hectorerb @Gianfranco97 Do you know something about it?

**Comment by hectorerb** [comment]
@CharlyJazz it can be useful [How to load string resources](https://msdn.microsoft.com/en-us/library/windows/apps/hh465248.aspx)

**Comment by CharlyJazz** [comment]
@hectorerb  The first paragraph is this: "[This article is for Windows 8.x and Windows Phone 8.x developers writing Windows Runtime apps. If you're developing for Windows 10, see the latest documentation]
"

:disappointed:
