### ISSUE TITLE
Get password complexity requirements from GLPI

### ISSUE THREAD

**Issue by btry** [flyve-mdm/web-mdm-dashboard#302]
I'm creating my own account with the Demo plugin.
  
### Observed Results:
I set the minimum length of the password to 5 chars in GLPI

![image](https://user-images.githubusercontent.com/14139801/36018380-dadf438a-0d7b-11e8-9909-25155b40a1c0.png)

  
### Expected behavior:

the dashboard must match the GLPI rules.

**Comment by Gianfranco97** [comment]
the dashboard is already following the rules of the glpi configuration

![captura de pantalla 2018-02-14 a la s 4 53 31 p m](https://user-images.githubusercontent.com/19965590/36227695-40a71c6c-11a8-11e8-9082-47c8af537442.png)

**Comment by btry** [comment]
What if you change the password minimal length in GLPI to 5 Will the dashboard complain with even shorter password and say I have to choose 5 chars a string ?

**Comment by Gianfranco97** [comment]
Sure, for example, raising the minimum to 10

![captura de pantalla 2018-02-14 a la s 5 18 02 p m](https://user-images.githubusercontent.com/19965590/36228709-57b9adc2-11ab-11e8-82ac-48d850ea0499.png)

**Comment by btry** [comment]
ok,  then I was facing a persistence problem. AS these settings will not change often, don't bother with this, keep the issue closed.
