### ISSUE TITLE
Error in I18N

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/web-mdm-dashboard#347]
### Observed Results:

At the moment of opening the application after being compiled, it generates the following error:

![captura de pantalla 2018-02-21 a la s 12 25 26 p m](https://user-images.githubusercontent.com/19965590/36491946-61626132-1702-11e8-8051-7ac8c62e925e.png)

![captura de pantalla 2018-02-21 a la s 12 25 18 p m](https://user-images.githubusercontent.com/19965590/36491948-61e778d6-1702-11e8-8379-572930a2e44b.png)

To solve this I had to leave temporarily commented the following lines of code in the file `withI18NTranslation.js`

- https://github.com/flyve-mdm/web-mdm-dashboard/blob/b711bf90b57766d0ebedf73e8f0c7195c356b85f/src/i18n/withI18NTranslation.js#L4
- https://github.com/flyve-mdm/web-mdm-dashboard/blob/b711bf90b57766d0ebedf73e8f0c7195c356b85f/src/i18n/withI18NTranslation.js#L10

**Comment by CharlyJazz** [comment]
Update the webpack package to the version 4 and keep the non-zero configuration of create-react-app and try to generate this error.
