### ISSUE TITLE
#ERROR_APP_TOKEN_PARAMETER on login

### ISSUE THREAD

**Issue by Philippe-M** [flyve-mdm/web-mdm-dashboard#356]
After start and the first login after build when i'm try to create a administrator account, i've this error

`le paramètre app_token est manquant; Afficher la documentation dans votre navigateur à http://glpi.xxxxxxx/apirest.php/#ERROR_APP_TOKEN_PARAMETERS_MISSING`

I modify a config.js file with the url and token for my glpi (9.1.7.1) installation.

**Comment by Gianfranco97** [comment]
@Philippe-M you must have installed the demo plugin in your glpi to be able to create new accounts in the dashboard

**Comment by Naylin15** [comment]
Hi @Philippe-M 

This is the documentation to install:

* [Demo plugin](http://flyve.org/demo-mode/howtos/installation)
* [Flyve MDM plugin](http://flyve.org/glpi-plugin/howtos/installation-wizard)

**Comment by Gianfranco97** [comment]
@Philippe-M The function responsible for registering users is this:
https://github.com/flyve-mdm/web-mdm-dashboard/blob/20fefd75d51f08327d51374b87c07f627716d5b9/src/Login/SignIn/index.js#L127

validate what data you are sending

**Comment by Gianfranco97** [comment]
Since we have not received any new feedback for this issue, we closed it.

If you have any new information please let us know

**Comment by simonipd** [comment]
Hello,

I have an urgent question
Is flyve mdm for android still working only with GLPI version 9.2.1 and earlier versions or for example with the current GLPI 9.3.4 official?

**Comment by simonipd** [comment]
> Hola @ Philippe-M
> 
> Está utilizando una versión anterior de GLPI y el complemento Flyve MDM, la demostración funciona con GLPI 9.2.1 y el complemento Flyve MDM v2.0.0-dev
> 
> Esta es la documentación para instalar:
> 
> * [Complemento de demostración](http://flyve.org/demo-mode/howtos/installation)
> * [Complemento Flyve MDM](http://flyve.org/glpi-plugin/howtos/installation-wizard)

I have an urgent question
Is flyve mdm for android still working only with GLPI version 9.2.1 and earlier versions or for example with the current GLPI 9.3.4 official?
