### ISSUE TITLE
Implement CSS Architecture

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/web-mdm-dashboard#369]
### Observed Results:

The projects do not have any structure to manage the CSS and are a mess
  
### Expected behavior:

[ITCSS Architecture](https://www.xfive.co/blog/itcss-scalable-maintainable-css-architecture/)

![image](https://user-images.githubusercontent.com/12489333/36637945-21006be4-19bd-11e8-96c7-e8ef06c3bfbe.png)

The implementation of an inverted triangle architecture would exponentially improve the maintainability of the project

[Repository with a example of ITCSS folder structure](https://github.com/CharlyJazz/Architecture-CSS)

Preview of tree folder:
![image](https://user-images.githubusercontent.com/12489333/36637986-20086998-19be-11e8-8736-93324a04a090.png)
![image](https://user-images.githubusercontent.com/12489333/36637996-5d0d1c8a-19be-11e8-80d1-bc0eb230fe6b.png)

Also a naming convention is very useful to standardize the name of the classes:
[BEM](https://css-tricks.com/bem-101/)

**Comment by CharlyJazz** [comment]
Please @rafaelje add this task to the issue #367 and asign it

**Comment by CharlyJazz** [comment]
Coming soon:

![image](https://user-images.githubusercontent.com/12489333/36643725-1797f414-1a26-11e8-81ad-fb0c0dafb06c.png)

**Comment by rafaelje** [comment]
@CharlyJazz Keep this task alone is not required for the first refactor this is a big task

**Comment by CharlyJazz** [comment]
@rafaelje Perfect, then

**Comment by ajsb85** [comment]
Hi, @Naylin15 
Could you add the link of the site for the architecture?
And use "ITCSS Architecture" in the description.
Thank you.

https://www.xfive.co/blog/itcss-scalable-maintainable-css-architecture/
![image](https://user-images.githubusercontent.com/663460/37235506-6c0bc38a-23ff-11e8-9b23-086cca5f6043.png)
