### ISSUE TITLE
PR missing for a branch

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/web-mdm-dashboard#385]
Hi, @Gianfranco97 

I can see the branch `file-structure-dashboard-hoc` without any PR related.
Could you delete this branch or create the PR as WIP?

Thanks

**Comment by Gianfranco97** [comment]
That branch contains some changes I had made on the refactoring, but these changes are meaningless after the progress made on it since the last time I worked on it. So I've already deleted the branch.
