### ISSUE TITLE
Delete Utils/ folder

### ISSUE THREAD

**Issue by CharlyJazz** [flyve-mdm/web-mdm-dashboard#419]
### Observed Results:

This folder not should exist
### Expected behavior:

The components in this folders should pass to components/ folder and the functions in share/

**Comment by Gianfranco97** [comment]
Done 


![captura de pantalla 2018-03-20 a la s 10 43 19 a m](https://user-images.githubusercontent.com/19965590/37661614-a04407d2-2c2b-11e8-89aa-5856481e84e9.png)
