### ISSUE TITLE
Styles of the forms

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/web-mdm-dashboard#424]
### Observed Results:

![captura de pantalla 2018-03-06 a la s 10 46 49 a m](https://user-images.githubusercontent.com/19965590/37038638-ba5de5f8-212b-11e8-8410-1c8e950e553c.png)

  
### Expected behavior:

- Increase the size of the menu icons
- Fix the column system
- Pass the names of the classes used to follow the rules of [BEM](http://getbem.com/naming/)

**Comment by ajsb85** [comment]
Hi, @Naylin15 
>Pass the names of the classes used to follow the rules of BEM
It is good material for the contributing guidelines.
