### ISSUE TITLE
package upload UX

### ISSUE THREAD

**Issue by btry** [flyve-mdm/web-mdm-dashboard#540]
If I upload an APK the list of APK displayed on the left pane is not refreshed.

## steps to reproduce
browse to the packages list
click the + button
pick an APK on the FS
click "save" button

## actual
list of apk not refreshed 
uploaded file still in the list of files to be uploaded (a line with a bin)
I can click again the save button, this will send again the file

## expected
 a successful upload should show 
the successfully uplaoded file should disappear from the upload

**Comment by Gianfranco97** [comment]
This problem is currently fixed

![jf23i-8vv30](https://user-images.githubusercontent.com/19965590/38740304-3d3e9304-3f05-11e8-92ca-4800fd53a10f.gif)
