### ISSUE TITLE
Massive edit action on package

### ISSUE THREAD

**Issue by btry** [flyve-mdm/web-mdm-dashboard#542]
If I try to massively edit packages I see Fleet name in the input box

![image](https://user-images.githubusercontent.com/14139801/38037297-df6b7bba-32a8-11e8-9809-a5215e0157f8.png)

**Comment by Gianfranco97** [comment]
Done in this PR: #322

**Comment by hectorerb** [comment]
Hi @btry you are editing a package with no name, 'Fleet name' is placeholder of the input

**Comment by btry** [comment]
Yes, this is the placeholder displayed before I type anything
