### ISSUE TITLE
Continuous Deployment with GitLab CI

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/web-mdm-dashboard#573]
Hi, we have many restrictions in our Virtual Machines in Teclib Hosting.
Proxies and VPN for the SSH access.
So, we will use the GitLab Runner to deploy the demo and the development version of the Web Dashboard.

- [x] Install and Start the GitLab Runner in the VM 169 (@DIOHz0r)
- [x] Add the gitlab-ci.yml to deploy the build (@hectorerb)

Mirror
https://gitlab.com/flyve-mdm/web-mdm-dashboard

Develop deploy
https://dev.flyve.org

References:
https://docs.gitlab.com/runner/
https://about.gitlab.com/features/gitlab-ci-cd/
https://docs.gitlab.com/ee/ci/quick_start/

**Comment by ajsb85** [comment]
Thank you @DIOHz0r

**Comment by ajsb85** [comment]
Hi, @hectorerb 

Here is the mirror of the repository:
https://gitlab.com/flyve-mdm/web-mdm-dashboard

**Comment by ajsb85** [comment]
The URL to see the deploy of the development version (develop branch)

https://dev.flyve.org

**Comment by ajsb85** [comment]
Hi, @btry 
Could you reconfigure the GitLab Runner in this repository?
https://gitlab.com/flyve-mdm/web-mdm-dashboard
Thank you.

**Comment by Gianfranco97** [comment]
This task is now ready
