### ISSUE TITLE
Page Not Found error

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/web-mdm-dashboard#601]
Hi, I want to report some minor errors in the 404 page.

### Observed Results

![image](https://user-images.githubusercontent.com/663460/38375990-d1d10196-38f7-11e8-9405-c032bf911c95.png)

![image](https://user-images.githubusercontent.com/663460/38376004-debd5c24-38f7-11e8-9c20-aa4ba5a307f6.png)

### Expected behavior

- A proper path of the logo URL.
- 2017-2018 as years of the public source code.

**Comment by Gianfranco97** [comment]
the route to the image seems to be fine to me, check your cache

**Comment by ajsb85** [comment]
I opened the URL in many different browsers

https://dev.flyve.org/dashboard

And the URL is wrong for the image

**Comment by ajsb85** [comment]
Actually the image point to:

https://dev.flyve.org/images/dashboard.svg

**Comment by Gianfranco97** [comment]
right, the cache problem was mine. I already found out what the problem was, I'll fix it in a moment
