### ISSUE TITLE
Feedback about the dashboard

### ISSUE THREAD

**Issue by btry** [flyve-mdm/web-mdm-dashboard#61]
Reported on Telegram by Mr. Papuaz

```
in the new generation dashboard. you need to lower down the react and react dom version to 15
otherwise the React.PropTypes isnt working :)

And another required hange is in the package.json
change to this:
 "react-winjs": "^2.5.0",
because using the link to the repo is false and never works
```

**Comment by hectorerb** [comment]
Hi @btry, we are using a modified version of react-winjs, to use react 16

https://github.com/flyve-mdm/web-mdm-dashboard/blob/e233357e30cc2e2bb62a4f32a0efdc6267fc9a5e/package.json#L44

**Comment by btry** [comment]
Hi

The suggestion would be to stick to version 15; maybe discussing Mr. Papuaz on Telegram may be useful to get more about his feedback.

**Comment by Gianfranco97** [comment]
Since we have not received any new feedback for this issue, we closed it.

If you have any new information please let us know
