### ISSUE TITLE
Buttons and sections titles both looks like a button

### ISSUE THREAD

**Issue by btry** [flyve-mdm/web-mdm-dashboard#627]
![image](https://user-images.githubusercontent.com/14139801/38486686-03564bde-3bde-11e8-8b2b-82ec7bfbac89.png)

![image](https://user-images.githubusercontent.com/14139801/38486697-0a1db092-3bde-11e8-982e-16ed88c8dfb4.png)

I suggest section titles have the maximum width (with maybe centered text)

![image](https://user-images.githubusercontent.com/14139801/38486816-69502a68-3bde-11e8-927f-17f2c6e9c128.png)

**Comment by DIOHz0r** [comment]
> I suggest section titles have the maximum width (with maybe centered text)

I suggest to improve the visual UI for the menu titles, first the cursor doesn't change to a pointer to let it know to the user that those are links for other options. Other idea would be if they have a green background like the buttons cause the bold style is not really helpful.
