### ISSUE TITLE
Crash when creating a file or an app

### ISSUE THREAD

**Issue by btry** [flyve-mdm/web-mdm-dashboard#634]
If I browse to files, and get this display

![image](https://user-images.githubusercontent.com/14139801/38488751-b3200db0-3be4-11e8-8e35-32f1c8e79c22.png)

I  try to create a file, clicking on the + button. The page updates to show a drag / drop area, and after 1 second, the dashboard crashes.

```
TypeError: _this.listView is undefined
FilesList/_this.handleAdd
src/containers/Files/components/FilesList.js:96

  93 |     this.props.history.push("/app/files/add")
  94 |     this.props.changeSelectionMode(false)
  95 |     this.props.changeSelectedItems([])
> 96 |     this.listView.winControl.selection.clear()
  97 | }
  98 | 
  99 | handleToggleSelectionMode = () => {

_handleClick
node_modules/winjs/js/ui.js:41940
```

**Comment by btry** [comment]
also noticed this in the dev tools
```Use of Mutation Events is deprecated. Use MutationObserver instead.```

**Comment by Gianfranco97** [comment]
Could you be more detailed in the steps to follow to get the error?

![ld5zd-obdu4](https://user-images.githubusercontent.com/19965590/38585758-0c3ceeea-3ce9-11e8-9a85-8958ffde81dc.gif)
