### ISSUE TITLE
Remove file and app policies added with empty values

### ISSUE THREAD

**Issue by Naylin15** [flyve-mdm/web-mdm-dashboard#641]
### Observed Results:
The user can add a remove file or app  policy with empty values (only once)

![empty-value](https://user-images.githubusercontent.com/30867977/38503602-87bdffaa-3be0-11e8-8621-61aea7a47e78.gif)

### Expected behavior:
A message requesting the value
Prevent the user from adding these policies with empty values

**Comment by Greenstonetr** [comment]
How Can I remove a file or application on Dashboard List( Files Applications).
give some errors
