### ISSUE TITLE
Incomplete list of fleets

### ISSUE THREAD

**Issue by DIOHz0r** [flyve-mdm/web-mdm-dashboard#657]
### Observed Results:

The number of fleets listed on GLPI are more than the showed on the dashboard

Using the glpi super admin you can see 15 fleets on the dashboard and there are 30 fleets on the backend
  
### Expected behavior:

The list of fleets must be completed

**Comment by hectorerb** [comment]
Hi @DIOHz0r 

The amount fleets in list is different for each account, Are you using the same account for both requests?

**Comment by hectorerb** [comment]
@DIOHz0r the amount for default is set on 15 for each request to searchItems, we could add a footer to load more fleets
