### ISSUE TITLE
Pull translations in the dev environment deployment

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/web-mdm-dashboard#663]
Hi, guys.

We need to install the tx CLI from Transifex in the VM of the Web Dashboard, to pull all translations and use it in the build for the beta deployment with the GitLab CI.
You can add the credentials in the secret vars of the GitLab repository

  
### Observed Results:

No translation resources
  
### Expected behavior:

Generate the list of all translations availables from Transifex.

**Comment by ajsb85** [comment]
Reference:
https://git.io/vxbt2

**Comment by Gianfranco97** [comment]
Solved with https://github.com/flyve-mdm/web-mdm-dashboard/pull/694
