### ISSUE TITLE
Lost password feature return a bad request status

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/web-mdm-dashboard#665]
Hi, guys.
I was trying to recovery my password and I got error in the console of the DevTools
```J
https://dev.flyve.org/glpi/apirest.php/lostPassword 400 (Bad Request)
```
Reference:
https://dev.flyve.org/dashboard/forgotPassword

**Comment by hectorerb** [comment]
hi @ajsb85 
What is the response? is this

`["ERROR", "Email address not found.; view documentation in your browser at https://dev.flyve.org/glpi/apirest.php/#ERROR"]`

**Comment by ajsb85** [comment]
Yes @hectorerb 
And I have an account. 
So the issue is related to the demo mode plugin.
I will move this issue.
Thank you, sorry.
