### ISSUE TITLE
Insecure content blocked

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/web-mdm-dashboard#761]
![image](https://user-images.githubusercontent.com/663460/39388553-3699b4de-4a81-11e8-9cc2-9121e86b9028.png)

**Comment by hectorerb** [comment]
Hi @ajsb85  
It's something that we will not be able to avoid at this moment, to obtain the profile image you need the cookies from glpi, we are using an iframe to go to https://dev.flyve.org/glpi/ and get the cookies

**Comment by ajsb85** [comment]
You should create the iframe and remove it.
We need to-do it to create the cookie.
So, it's an initial script, we don't need to call it any more.
