### ISSUE TITLE
"Profile Settings" and "Edit User" should be the same layout.

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/web-mdm-dashboard#79]
![image](https://user-images.githubusercontent.com/663460/33676220-6daa0988-dab5-11e7-961b-e7e43e51e703.png)

![image](https://user-images.githubusercontent.com/663460/33676234-79ac65e6-dab5-11e7-970f-c5ac426adbdd.png)

**Comment by Gianfranco97** [comment]
@ajsb85 Which designs do you prefer?

**Comment by ajsb85** [comment]
Profiles is more complete, but is missed the password fields.

Take a look in the GLPI profile page, to take the same fields 👍
