### ISSUE TITLE
Fleet tasks

### ISSUE THREAD

**Issue by FrankCumaio** [flyve-mdm/web-mdm-dashboard#809]
I was trying to activate tasks for a new fleet but it was showing a error "You don't have permission to perform this action".
But i was able to associate the tasks in the glpi dashboard and they even take effect on the mobile agent, but the flyve mdm dashboard doesn't show which tasks are activated on the fleet tasks list.

<img width="1439" alt="glpiscreen" src="https://user-images.githubusercontent.com/17769520/40015380-b0dcab10-57a2-11e8-9de1-bca3860757d3.png">
<img width="1439" alt="mdmdash" src="https://user-images.githubusercontent.com/17769520/40015381-b11ea542-57a2-11e8-9609-e996f44a23f4.png">

**Comment by hectorerb** [comment]
https://github.com/flyve-mdm/glpi-plugin/pull/502
