### ISSUE TITLE
Create account form

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/web-mdm-dashboard#91]
![image](https://user-images.githubusercontent.com/663460/33706569-d0925d1e-db34-11e7-94d3-c150777aaf19.png)

@btry How the Dashboard can detect if enable the self create account?

**Comment by btry** [comment]
The self creation of an account is useful only when the demo plugin is installed in the backend.

I think the dashboard shall just rely on the existence of an API key for the self service user in its configuration. If the API key is set then show the link to self-create an account. If there is no API key, don't show it.
