### ISSUE TITLE
Create docker container to test deploy

### ISSUE THREAD

**Issue by hectorerb** [flyve-mdm/web-mdm-dashboard#958]
Hi @ingluife,

Could you create a docker container to test build on development environment?
Docker container specification:
- Web serve Apache 2.4.x
- This config to [.htaccess](https://github.com/flyve-mdm/web-mdm-dashboard/blob/develop/htaccess_dev)

**Comment by ingluife** [comment]
Hi @hectorerb.

Yes, i do. I'll work in that today.
