### ISSUE TITLE
Cannot change Token Life

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/web-mdm-dashboard#967]
Hi, @flyve-mdm/frontend-development 
I was trying to edit the Token Life in the Config of the Entity.
https://dev.flyve.org/dashboard/app/settings/entity

User: asalas@teclib.com

![image](https://user-images.githubusercontent.com/663460/42690877-3d40fb88-86a6-11e8-8a63-c38144f933db.png)

```console
Uncaught (in promise) TypeError: Cannot read property 'setNotification' of undefined
    at t.<anonymous> (ChangeTokenLife.js:99)
    at i (runtime.js:86)
    at Generator._invoke (runtime.js:320)
    at Generator.e.(anonymous function) [as throw] (https://dev.flyve.org/dashboard/static/js/main.a7ce0881.js:1:2777977)
    at r (0.7bb66bca.chunk.js:72776)
    at 0.7bb66bca.chunk.js:72776
```

**Comment by Gianfranco97** [comment]
These are not problems of the dashboard, this relates to the level of access of your user. Observe the message that is delivered by server "You are not allowed to change the device limit".

![captura de pantalla 2018-07-13 a la s 6 43 53 p m](https://user-images.githubusercontent.com/19965590/42717299-071450d2-86ce-11e8-850a-35da6bb779aa.png)

**Comment by ajsb85** [comment]
Hi, @flyve-mdm/backend-development 
Why we cannot edit the Token Life?

**Comment by Gianfranco97** [comment]
**Request URL:** https://dev.flyve.org/glpi/apirest.php/PluginFlyvemdmEntityconfig/
**Request Method:** PUT
**Request Payload:** 
``` javascript
{input: [{id: "0", download_url: "https://test.test"}]}
```
