### ISSUE TITLE
Add new item Supervision in the Settings

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/web-mdm-dashboard#98]
![image](https://user-images.githubusercontent.com/663460/33708701-74dae138-db3b-11e7-8d34-fa20eed98ff2.png)

**Comment by ajsb85** [comment]
Hi, @hectorerb 

Could you provide screenshots of the PR #152?

Thanks.

**Comment by Gianfranco97** [comment]
![localhost_3000_app 5](https://user-images.githubusercontent.com/19965590/34301602-a0206c36-e703-11e7-83c9-4485b93b8794.png)


  ![localhost_3000_app 6](https://user-images.githubusercontent.com/19965590/34301604-a14db85c-e703-11e7-9642-ae5cde11e47a.png)
